#pragma once
#include <eigen3/Eigen/Dense>
#include <assert.h>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <queue>
#include <random>
#include <regex>
#include <string>
#include <type_traits>
#include <vector>
